### ISSUE TITLE
Should empty query entry assume all available options for this query?

### ISSUE THREAD

**Issue by MartinFXP** [dirmeier/rnai-utilities#9]
E.g. if I put 
`
res = q.query(library="", featureclass="cells", gene="star", sample=10)
`
nothing is written (or just a bug on my side?). But what it should do is get 10 cells for star from each well regardless of library, right?

**Comment by dirmeier** [comment]
Hello Martin, if I recall correctly the query you submit is printed to stdout? There you should see what is happening. If you want all libraries, just dont enter the parameter.

Best,
Simon
